version: '3.8'

services:
  raredisease-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raredisease-chatbot
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      # Mount data directory to keep documents accessible
      - ./data:/app/data:ro
      # Persist ChromaDB data
      - chroma_data:/app/chroma_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  chroma_data:
